# This is a basic workflow to help you get started with Actions

name: CI with Maven

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.8.6' ]
        java: [ '17' ]

    name: Maven ${{ matrix.maven }} sample

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK version
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # Runs a set of commands using the runners shell
      - name: Step 3 - Build Maven Project
        run: |
          mvn validate
          mvn install

      - name: Step 4 - Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Step 5 - List the current directory
        run: ls -a

      - name: Step 6 - What is in the target folder?
        run: | 
          cd target
          ls -a
